spring:
  application:
    name: LetsChat

# Database Connectivity
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

# Server Port
server:
  port: 8080

# File
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

